- doc/usage.rst
The example in the docs of creating a `pysam.AlignedSegment` no longer works under `v0.8.1`.This is because the `query_qualities` can no longer be set as a string.
I'm not sure what the preferred approach is for setting the `query_qualities`. I am using `pysam.fromQualityString()` but it could equally be hand-coded using `array.array()` with the type set to `B`.
> Example `pysam.AlignedSegment` needs fixing under `v0.8.1`

- pysam/ctabix.pyx
Just correcting an oversight - the '%s' was already in the message, it just wasn't getting filled.
> added filenames in error messages of tabix_compress.

- doc/index.rst
The current version of pysam (0.8.2) has already been updated to htslib 1.2.1, but the docs still say it wrap htslib 1.1. This updates the dos to reflect that reality.
> Updates docs to reflect htslib 1.2.1

- pysam/cbcf.pyx
This is a straw-man partial implementation of providing access to `hts_verbose`, so we can control when messages are written to the low-level file descriptors. (See issue #88).
Problems with this PR:
1. It doesn't work. I haven't been able to figure out how to get the linkage for the extern hts_verbose variable to work. It remains set to 3 no matter what I do. If this is a genuine problem (and not just my Cython idiocy), perhaps we should open an issue with htslib where they provide functions to get and set the verbosity instead of requiring us to use a global variable?
2. This is in the wrong file. I think this functionality probably belongs in `chtslib.pyx`, but I couldn't get the compiler to see `hts_verbose` if  I put it in there. 
I'm new to Cython, so any pointers would be much …
> Straw-man implementation of hts_verbose access.

- pysam/calignmentfile.pyx
- tests/AlignedSegment_test.py
Get_aligned_pairs was broken for softly clipped reads, and match/mismatch CIGAR commands.
I added test cases for all CIGAR commands.
Padding (6 - BAM_CPAD) is still unsupported, but now raises a NotImplementedError.
Also, I've integrated my recently suggested get_aligned_pairs_matches_only() which allows great speed ups if all you care about is actually read bases.
> Almost all CIGAR and optional matches_only for read.get_aligned_pairs()

- doc/api.rst
- pysam/calignmentfile.pyx
This is the simple doc change that reflects Pileupread.query_positions undefiniedness when there is no query sequence to the alignment at this position.
> Query position doc change

- doc/api.rst
- pysam/calignmentfile.pyx
This change returns None for query_position when a PileupRead is a deletion or reference skip at this reference position.
See bug #93
> Pileup read.query position none

- pysam/calignmentfile.pyx
- tests/AlignedSegment_test.py
This adds the `AlignedSegment.is_supplementary` property. I was not able to run the tests, unfortunately (TestUtils could not be imported and various other errors), but I believe this to be straightforward enough.
> Add an is_supplementary attribute to AlignedSegment.

- pysam/calignmentfile.pyx
This adds an implementation of `__richcmp__` so one can compare AlignedSegments to each other. I’m relying on the already existing `compare()` method. Since it’s not clear what the comparison result should be if other operators such as `<` and `<=` are used, I left them out for now.
I still don’t know how to get the unit tests running (as I mentioned in the last pull request), so I haven’t added any.
> Make AlignedSegments comparable

- pysam/calignmentfile.pyx
When using `iter = fetch(reference = "...")` and then iterating over `iter`, paired reads with mates on other references are never encountered even though they exist: `read.reference_id == read.next_reference_id` for **all** reads examined this way.
Iterating on the AlignmentFile itself (using the same file) does find pairs with mates on different references (so there are now reads for which `read.reference_id == read.next_reference_id` is **not** true).
> fetch(reference=...) does not return mates on a different reference

- htslib/cram/cram_index.c
- pysam/calignmentfile.pyx
- pysam/ctabix.pyx
- save/pysam_test2.6.py
- tests/AlignmentFile_test.py
- tests/SamFile_test.py
Debian QC tools complained about spelling errors in the source
code. This patch corrects them.
> Fix various spelling errors

- pysam/calignmentfile.pxd
- pysam/calignmentfile.pyx
Would you be receptive to a change along these lines?  Getting the type of a tag value is important to us.  I can add some tests.
> get_tag: expose tag type if requested with `with_value_type`

- pysam/cvcf.pyx
I believe this fixes issue #130, passing encoding correctly to `TabProxies.TupleProxy`.
> Fix for #130

- pysam/calignmentfile.pxd
- pysam/calignmentfile.pyx
Added tostring() method to AlignedSegment using its matched AlignmentFile. (See https://github.com/pysam-developers/pysam/issues/125)
This is motivated by issues with AlignmentFile's flexibility in writing - it fails to write the headers for its plain text files. You can manually write it to a stream (handle.text), but not to a file because AlignmentFile doesn't have a "w+" option, so any file header gets clobbered (and so the answer is a stream).
I also often get memory allocation issues when moving AlignedSegment_t objects around, and so when I've processed reads but sometimes want to output my new text or the read's texts, I end up with two streams. (In fact, the AlignedSegment from scratch example in the docs works for me to write, but segfaults when I try to read that file.) Of …
> AlignedSegment to valid SAM record string

- README.rst
pysam test builds are done on [Travis CI](https://travis-ci.org/pysam-developers/pysam) but there is no build status image on the [README.rst](https://github.com/pysam-developers/pysam/blob/master/README.rst) file.
> Add pysam travis ci build status image

- pysam/calignedsegment.pyx
Apparently, an array of length 1 without a terminating comma is viewed as an incompleted aux field. Modified TagToString for this edge case.
> Patch for an edge case in array packaging/unpackaging.

- tests/pysam_data/Makefile
The samtools pileup command has been superseded with the mpileup subcommand. The corresponding
flags have changed as well.
----
Please see our patch header at http://anonscm.debian.org/cgit/debian-med/python-pysam.git/tree/debian/patches/sam_mpileup.patch
for a more detailed description.
> Update depricated command in test suite

- pysam/calignmentfile.pyx
The SAM specification advises as best practice to avoid use of custom upper-case header record tags without requesting their addition to the specification, but the spec does not preclude their addition or use. This pull request simply alters the header record parsing behavior to support this.
Happens to be related to #71.
o7
> Removes exception for custom upper-case header record tags.

- pysam/calignedsegment.pxd
- pysam/calignedsegment.pyx
- pysam/calignmentfile.pyx
PileupColumn also gets a reference_name attribute. For this to work,
both AlignedSegment and PileupColumn gain an _alignment_file attribute.
No need to call getrname anymore in user code!
I cannot get the tests to run locally, so there aren’t any test cases, yet. I’m opening this PR already now to get feedback from Travis.
Another possibility of implementing this would be to only have a reference_name attribute, but the approach with the alignment_file attribute is more generic. For example, I haven’t implemented a setter for reference_name, yet, but to do that, it will also be necessary to access the AlignmentFile.
> Add reference_name and next_reference_name attributes to AlignedSegment

- pysam/calignmentfile.pyx
(when not raising an exception) as defined in the docstring.
> Fixes AlignmentFile.check_index to return True

- pysam/ctabix.pyx
Tabix is not thread-safe and the GIL should not be released while querying.
In my case, I was running a Tornado web server with several threaded workers that performed Tabix queries simultaneously.
This would result in error messages from the Tabix C-library such as this:
```
[E::get_intv] failed to parse TBX_GENERIC, was wrong -p [type] used?
The offending line was: "	+	NM_012231	6	intronic	CDS	238	682833521792	34873960360784	iffffffffffffffffff”
```
The error message indicated that lines from the indexed file where read incompletely and the issue disappeared when I switched to using just a single worker.
The attached patch solved the issue for me.
> Do not release GIL when querying Tabix

- pysam/calignedsegment.pyx
Currently the docs on `get_aligned_pairs()` appear misformatted (http://pysam.readthedocs.org/en/latest/api.html#api).  I think my changes fix them.  The remaining change should just be whitespace cleanup by my editor.
> Fix docstring in aligned pairs

- pysam/calignmentfile.pyx
Just eyeballing, this looks like a minor bug - please reject if irrelevant!
> Incorrect cram file name trim on index discovery

- doc/api.rst
The two for loops were rendered as separate loops instead of being nested (at http://pysam.readthedocs.org/en/latest/api.html)
> Fix rendering error on readthedocs

- pysam/calignedsegment.pyx
Currently `get_tags(with_value_type=True)` returns a tuple of (two characters, value, integer type). So an auxiliary tag like `AS:i:1` is returned as `('AS', 1, 67)` rather than `('AS', 1, 'C')`. This PR just puts things through `chr()`, which should solve the problem. I assume that this issue only arises due to how Cython dealt with the code previously.
> get_tags() should return the tag type as a character, not an integer

- MANIFEST.in
- cy_build.py
- pysam/__init__.py
Hello,
I'm a software developer at Invitae, and we've been using pysam for quite some time. Recently I saw an update on the 0.8.5-dev branch that supports linking to pysam .so files on Mac. This made it possible for us to port an internal library to Mac. In the course of that project, I modified cy_build.py to:
a. work with pip (the current implementation depends on easy_install's egg placement)
b. work with develop mode (either `python setup.py develop` or `pip install -e`)
c. use the `@rpath` flag within the clang linker's `install_name` so shared libraries do not contain the full path of the virtual environment, if any, in which they were built.
I hope these changes are helpful, please reach out to me if you have any questions, suggestions for improvement, etc. Keep up the great work.
> Update cy_build.py to support pip and develop mode on Mac.

- pysam/cbcf.pyx
- tests/tabix_test.py
This PR adds the most glaring missing functionality from cbcf -- getting and setting genotypes on samples.  It also adds:
- id/key string caching/interning
- support for Flag types
- setting alleles from any mixture of indices and strings
- a few more Py3 fixes
tests/tabix_test.py no longer fails, provided remote data are available.
@AndreasHeger : Please merge prior to release of 0.8.5.  
My next goals are to:
- translate my large suite of ad hoc testing code into UnitTests (ETA later this week)
- support header translation to allow records from one file (with one header) to be written to another file (with a different header) (ETA next week)
- complete mutating support by allowing creation of new records and adding samples to existing records (ETA next week)
- add support to htslib and …
> Add missing cbcf functionality

- doc/api.rst
- pysam/cfaidx.pyx
I found and corrected a number of issues related to fastq parsing docs:
1.  The conversion from `FastqFile` to `FastxFile` was not propagated to `api.rst`, so there were no API docs on opening fastq files.
2.  The docstring on FastxFile had no example, making it hard to figure out what structures were returned by the streaming iteration.
3.  The fastqproxy object was not included in the API docs.  
4.  The fastqproxy object had no docstrings on its various accessor properties.
5.  The conversion from fastqfile to fastxfile wasn't really documented in the docstrings.
6.  The old fastqfile object has zero docstring information when examined by python help.  
7.  Various fixes to whitespace (sorry, my editor makes me do it).
> Clean up docs for fastxfile and fastqproxy

- pysam/calignmentfile.pyx
- pysam/chtslib.pxd
The reference_filename parameter to the AlignmentFile constructor is now
also interpreted when opening a CRAM file for reading, not only when writing.
Closes #280
> Allow specifying a FASTA reference when reading a CRAM file

- pysam/calignedsegment.pyx
There is no docstring on the `is_refskip` property on pileup reads.  I added the following one, but I am not 100% sure if my interpretation is correct:
"1 iff the base on the padded read is skipped in the reference, i.e. an insertion"
> Fix docstring in refskip

- bcftools/vcfisec.c
- bcftools/vcfisec.c.pysam.c
- pysam/calignedsegment.pyx
- pysam/calignmentfile.pyx
The package linter picked these up and the notices don't go away without being fixed :)
> Fix spelling/grammar issues found using Debian QA tools

- pysam/cutils.pyx
Hello,
Pysam's `fetch()` methods accept `bytes` from Python 3 and Python 2 callers, but only accept Unicode from Python 3 callers. This is because `pysam/cutils::force_bytes()` behaves differently under Python 2 than it does under Python 3.
In Python 3, `force_bytes()` converts a string or unicode object to bytes. In Python 2, it does nothing. This leads to unusual behavior: for instance, in Pysam 0.8.2.1, `AlignmentFile.fetch(u"1", 0, 100)` will raise a TypeError ("Expected bytes, got unicode") but the same call on a FastaFile object will succeed. (This seems to be a happy accident due to some string interpolation in the FastaFile method that was removed sometime before pysam 0.8.4. As of 0.9.4, neither method accepts unicode from Python 2.)
The Python 3 guard has been present for a long …
> Make force_bytes() behave the same on Python 2.7 as it does on 3.x.

- pysam/calignedsegment.pyx
Quick change to the query_length method docstring as infer_query_length is in AlignedSegment not AlignmentFile plus errant '.'
> Update calignedsegment.pyx docstring for query_length

- pysam/calignedsegment.pyx
- tests/AlignedSegment_test.py
https://github.com/pysam-developers/pysam/issues/332
BAM_CHARD_CLIP ops in cigar are now used as part of calculation to infer original query length.  I have also added a test for infer_query_length().
> Fix for #332: Hardclipped bases in cigar ignored by pysam.AlignedSegment.infer_query_length()

- pysam/calignedsegment.pyx
- tests/AlignedSegment_test.py
Reverts pysam-developers/pysam#338
> Revert "Fix for #332: Hardclipped bases in cigar ignored by pysam.AlignedSegment.infer_query_length()"

- pysam/calignedsegment.pyx
- tests/AlignedSegment_test.py
Reverts pysam-developers/pysam#339
> Revert "Revert "Fix for #332: Hardclipped bases in cigar ignored by pysam.AlignedSegment.infer_query_length()""

- setup.py
When running make print-config first row contains
make[1]: Entering directory `/tmp/pip-build-eXV8ja/pysam/htslib'
This makes current code break.
> Install fails on Ubuntu 14.04 when using pysam as requirement for other module

- .travis.yml
- run_tests_travis.sh
Allegedly, switching off the sudo access will migrate our Travis builds to the newer container-based infrastructure (https://docs.travis-ci.com/user/migrating-from-legacy/).  I believe this may improve CI speed and may also enable local reproducibility (YMMV).
I've also added some minor cleanup to the CI to enhance readability.
> [WIP] Enable container infrastructure for Travis

- htslib/htslib/knetfile.h
Compilation of pysam (HEAD and 0.9.1.4) with musl libc on Alpine Linux breaks due to missing type declarations in htslib/htslib/knetfile.h: 
```
gcc -fno-strict-aliasing -Os -fomit-frame-pointer -g -DNDEBUG -Os -fomit-frame-pointer -g -fPIC -Ipysam -I. -Ihtslib -I/usr/include/python2.7 -c pysam/htslib_util.c -o build/temp.linux-x86_64-2.7/pysam/htslib_util.o -Wno-unused -Wno-strict-prototypes -Wno-sign-compare -Wno-error=declaration-after-statement
In file included from pysam/htslib_util.c:7:0:
htslib/htslib/knetfile.h:88:2: error: unknown type name 'ssize_t'
ssize_t knet_read(knetFile *fp, void *buf, size_t len);
^~~~~~~
error: command 'gcc' failed with exit status 1
```
The attached commit adds the necessary include to allow compilation in this environment.
> Fix compilation with musl libc

- buildwheels.sh
As discussed in issue #344, it would be great if wheels for pysam were available. Pysam is quite a heavy dependency, and it is one of those packages for which offering wheels would therefore really pay off by reducing installation time.
This script is based on the [manylinux1 demo](https://github.com/pypa/python-manylinux-demo). It uses docker to build binary, manylinux1 wheels. It is meant to be run locally for now. The wheels are put into a `wheelhouse/` directory, and someone with access to the PyPI account then needs to upload them (I guess with `twine upload`).
The only limitation is that HTTPS and S3 URLs are not supported because this would mean that OpenSSL needs to be bundled into the wheel, which in turn would make pysam developers responsible for updating the wheels when there …
> Script for building manylinux1 wheels

- setup.py
It's already initialized earlier in the script.
> setup.py: remove redundant setting of HTSLIB_MODE

- pysam/libcbcf.pyx
- pysam/libchtslib.pyx
- pysam/libcutils.pyx
- tests/VariantFile_test.py
Support Python 3.6 file system path protocol (using os.fsencode, available since Python 3.2).  Also fix remaining flaw preventing solution to #355 from working for VariantFiles.
> Support Python 3.6 file system path protocol

- pysam/libcalignedsegment.pyx
This seems to fix the issue I reported in #406. In short, for arrays the `valuetype` is always going to be set to `B`, which won't be appropriate for the type of the array. This code changes this to the type of the array or `None` if that's not a known type (e.g., if a known type ends up getting stored as something else...the ZM tag in my original example in #406 is such a case) then this is changed to `None` and generated as needed. It's likely that this means that some of the other code in `packTags()` is no longer needed.
> Attempt to fix #406

- pysam/libcbcf.pxd
- pysam/libcbcf.pyx
The error in calling `bcf_get_genotypes` was due to a last minute cleanup that wasn't valid.  The remainder are:
* fix a few ordering issues, which are side-effects of developing under Python 3.6 where all dicts are ordered.
* fix return type of `pop()` method.
* Make `header` attributes public/readonly.
* rename `VariantContig.header` property to `header_record` due to conflict with the previous change.
* Allow filter initialization of `VariantRecordFilter` in `VariantHeader.new_record` from another `VariantRecordFilter` instance.
Hopefully a run through Travis will pick up any residual issues.
> Fix error in calling `bcf_get_genotypes` and a few other more minor glitches

- doc/release.rst
- pysam/libcbcf.pyx
A pysam user has privately reported a bug with the VariantRecord class.  The
situation is somewhat complicated, but the root cause is that `INFO/END` is
able to get out of sync with the `VariantRecord` stop coordinate.  After
trying several simpler workarounds, it seems that the best solution is to
not expose `INFO/END` via `VariantRecord.info`.  This is because it is an
artifact of the VCF text format that isn't used in BCF or the htslib
in-memory representation.  Instead, all access is via `VariantRecord.stop` and
`VariantRecord.rlen`, while `INFO/END` is kept in sync behind the scenes.
In fixing researching and this bug, I've also found and fixed several other
bugs in VariantRecordInfo:
* scalar INFO entries could not be set again after being deleted
* multiple cases where access to …
> Multiple fixes related to VariantRecordInfo and handling of INFO/END

- pysam/tabix_util.c
Fixes this problem:
~~~~
gcc -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -fwrapv -O3 -Wall -Wstrict-prototypes -MD -I/sw/include -Ipysam -I. -I/sw/include -I/sw/include/python2.7 -c pysam/tabix_util.c -o build/temp.macosx-10.11-x86_64-2.7/pysam/tabix_util.o -Wno-unused -Wno-strict-prototypes -Wno-sign-compare -Wno-error=declaration-after-statement
pysam/tabix_util.c:20:3: warning: implicitly declaring library function 'memset' with type 'void
*(void *, int, unsigned long)' [-Wimplicit-function-declaration]
memset(*line, 0, *linelen);
^
pysam/tabix_util.c:20:3: note: include the header <string.h> or explicitly provide a declaration
for 'memset'
pysam/tabix_util.c:23:11: warning: implicitly declaring library function 'strlen' with type
'unsigned long (const char *)' …
> remove implicit declarations on memset and strlen

- cy_build.py
- run_tests_travis.sh
This is somewhat of an experimental PR to solicit some feedback on an issue with building pysam eggs/wheels on mac OS. The issue is that the current configuration in [cy_build.py](https://github.com/pysam-developers/pysam/blob/d41a7c87d93f50277f4a2d1f0efc07fa19954963/cy_build.py#L80) will cause the absolute path to the interpreter to be used in the libraries' rpath, and this makes an egg/wheel unshareable between different machines, or even different Python installations on the same machine. 
To see this in more detail:
1) Build a wheel; `python setup.py bdist_wheel`
2) Unpack the egg; `cd dist && unzip pysam*.whl`
3) Inspect the rpath for any of the shared libraries (note the absolute path):
```
$ otool -l pysam/libcutils.*.so | grep -A2 LC_RPATH
cmd LC_RPATH
cmdsize 88
path …
```
> Use @loader_path for mac OS library paths

- htslib/vcf.c
`bcf_translate` works correctly on newly created or loaded BCF records, but it does not properly account for records which have been modified by having one or more INFO fields deleted.
Prior to attempt to update the info value (either in place or after resizing), update the entry's key id (to keep all ids valid) and then check whether `line->d.info[i].vptr` is `NULL`.   This indicates that the key and value have been deleted.  Otherwise, `vptr` is incorrectly assumed to point to a valid value and a segmentation fault results.
`bcf_translate` uses a data structure stored within the source BCF header data structure.  This is a poor design decision, because it presumes that any header will be used to translate to no more than one destination header.  Worse, there is no check to verify that …
> Fix bcf_translate to skip deleted INFO fields to avoid segfaults

- pysam/libcfaidx.pyx
- run_tests_travis.sh
- setup.cfg
- tests/AlignmentFile_test.py
- tests/TestUtils.py
- tests/VariantFile_test.py
- tests/compile_test.py
- tests/tabix_test.py
Running tests with nose would use the `tests` directory as CWD, so test file paths were all relative to the `tests` directory.  In contrast, pytest runs from the `pysam` base directory as CWD, so all test file file paths must be updated.  Prior changes were sufficient to ensure that existing test files were found in the correct locations, but many temporary files were created in CWD, rather than the `tests` directory.  
- There are still a few temp files not created in `tests`, including the 1kGenomes index file.
- In future, all temporary files should probably be written to a dedicated directory that can be removed after the test suite is run.
> Fix temp file paths used in tests

- doc/glossary.rst
- pysam/htslib_util.c
- pysam/libcalignedsegment.pxd
- pysam/libcalignmentfile.pxd
- pysam/libcalignmentfile.pyx
- pysam/libcbcf.pyx
- pysam/libchtslib.pxd
- pysam/libchtslib.pyx
* Update glossary entry for CIGAR
* Correct error return in pysam_bam_update
* Remove incorrect use of inline declarations in external Cython definitions
* Refactor region_parsing and related code to HTSFile base class.
Doing so exposed a bifurcation in terminology.  `AlignmentFile` uses
`reference` and `end`, where as `VariantFile` is careful to always use
`contig` and `stop`.  Although there is more code in the wild using
`AlignmentFile`, I *strongly* prefer the latter nomenclature and updated all
of the code to use that.  However, extra keyword arguments were added to
enable backward compatible use of `reference` and `end`. 
I understand this change may be a bit controversial and I am happy to discuss before merging this PR.
> Refactor parse region

- pysam/libcalignmentfile.pyx
- pysam/libcbcf.pyx
- pysam/libcbgzf.pyx
- pysam/libcfaidx.pxd
- pysam/libcfaidx.pyx
- pysam/libchtslib.pyx
- pysam/libctabix.pyx
- pysam/libcutils.pyx
Restructure error handling in `FastaFile.fetch`, `FastaFile._fetch`, and `VariantFile.fetch` to expose IO errors by raising Python`IOError` exceptions when `errno` is set.  The intent is to address hidden data loss (Issue #504), clarify when IO errors are occurring, and incremental to being able to add retry logic.  Testing is difficult, since simulating IO errors is not trivial.
Also added some missing detection of BCF allocation failures and raise `MemoryException`.
`FastaFile.fetch` still raises `ValueError` for non-IO errors.  However raising `IOError` is a non-backward compatible change and may cause problems in practice.  To me, is justifiable in order to unobfuscate when IO errors occur.
> Expose IO errors via IOError exceptions

- tests/samtools_test.py
The usage() functions check whether stdin is a tty before displaying usage
information.  Therefore, we should not test this code when running on an
autobuilder without a tty.
Clever allocation of a pty from within the test suite itself for purposes
of testing this path is left as an exercise for the reader.
> skip usage() tests on autobuilders

- doc/release.rst
- pysam/libcalignmentfile.pyx
- pysam/libcbcf.pyx
- pysam/libchtslib.pyx
Substantially simplify index loading logic in `AlignmentFile._open`:
* Remove attempts to guess data and index file names; this is magic that I recommend we leave to htslib.
* Remove file existence check prior to opening files with htslib; do check for errors more carefully afterward and raise the appropriate error (`IOError` for when `errno` is set, `ValueError` otherwise for backward compatibility)
* Catch IO errors when explicitly loading an index.
* Allow remote indices (tested using S3 signed URLs, not easily added to the test suite).
* Document `filepath_index` and make it an alias for `index_filename`.
* Added a `require_index` parameter to `AlignmentFile`
> Simplify file detection logic and allow remote index files

- pysam/libcbcf.pyx
Hi,
I found a small bug in the updated `VariantHeader.new_record` method. When setting the record's initial attributes, the setters' calls to `bcf_sync_end` raise an exception because `record.ref` is `None`. 
I added a quick check in `bcf_sync_end` to handle this case. I think setting `ref_len` to 0 prior to the INFO/END deletion shouldn't have any side effects, since a new record shouldn't have any alleles or a set END anyways. 
This bug could also be solved by setting `ref` before setting the remaining attributes in `new_record`, but I wasn't sure what the desired default would be for `ref` (or if it would be a good idea to force a default).
> Handle unset ref when creating new records

- setup.py
* Gentoo builds all python packages out of tree,
as is best practice. Using `-Isamtools` implicitly
assumes that everything is being built inplace.
See also: https://bugs.gentoo.org/show_bug.cgi?id=629670
> Allow for building out of tree

- pysam/libcalignedsegment.pyx
Its possible that MD tag derived seqeunce length is longer than CIGAR
alignment length. In such cases, building alignment sequence can lead
to a buffer overflow error. Such reads will now generate an assertion.
> Assert on reads with invalid MD tags

- pysam/libcalignedsegment.pyx
Include insertion length along with the MD and CIGAR details in assert error
> Improve assert log for mismatched MD tag reads

- pysam/libctabix.pyx
- tests/tabix_test.py
This seems to be necessary to create TabixFile instances with indexes that don't end in `.tbi`.
> Allow loading index without tbi extension

- pysam/libcbcf.pyx
Hi,
I found a bug where it wasn't possible to set the `ref` of a newly constructed VariantRecord. In the absence of any defined alleles, the ref setter method sets the record's alleles to be the list of only the reference allele. However, the alleles setter method requires at least two alleles to be passed. I fixed this by providing a generic "NON_REF" allele along with the ref allele if no others are present.
> Provide default alternate allele when constructing a new VariantRecord

- pysam/libcalignedsegment.pyx
Closes #588.
Ensures that `AlignedSegment.get_reference_sequence` raises an exception when no MD tag is set.
> Return None from build_alignment_sequence if no MD tag is set

- pysam/libcalignmentfile.pyx
- pysam/libchtslib.pxd
- pysam/libchtslib.pyx
This implements #579 and additionally allows decoding specific fields in CRAM files (in the same was as `--input-fmt-option` and `--output-fmt-option` in `samtools view`).
Another possible implementation of this would be to use a `dict()` (I'm not sure what people will find more convenient).
N.B., it's inadvisable to use `required_fields=XXX` and then to attempt to use one of the unrequired fields (try it, you'll get some "interesting" results that I presume are an artefact from htslib).
> Add a format_options keyword to AlignmentFile

- pysam/libcbcf.pyx
- tests/VariantFile_test.py
- tests/cbcf_data/gnomad.vcf
- tests/cbcf_data/gnomad_fixed.vcf
Removing the assertion seems to enable the functionality without any side effects as far as I can see.
Would appreciate some comments though as I don't fully understand that part of the htslib API.
> {AH} permit Number=G in INFO records

- pysam/libcalignmentfile.pyx
- setup.py
Trying to fix issue [#603](https://github.com/pysam-developers/pysam/issues/603). In the ```AlignmentFile.count_coverage()``` method, if an alignment has an empty QUAL field, it raised a ```TypeError```.
I am fixing this by ignoring the quality threshold and counting every bases when an alignment has empty QUAL field. I am adding a warning for these kind of ```AlignedSegment```, so this issue is not silently passed. However, I am not sure if a warning is the best solution or if it should just raise a more clear error?
> Adding a warning to count_coverage when an alignment has an empty QUAL field

- pysam/libcalignedsegment.pyx
It turns out that if you try to use the `get_blocks()` function on a read with CIGAR string `150=` you'll get `[]` returned. This is due to a number of functions not handling the `=` and `X` operations. I've fixed that in the current PR.
> Ensure that = and X CIGAR ops are treated the same as M

- bcftools/bcftools.pysam.c
- bcftools/bcftools.pysam.h
- bcftools/tabix.c.pysam.c
- devtools/import.py
- import/pysam.c
- import/pysam.h
- samtools/bam.c.pysam.c
- samtools/bedcov.c.pysam.c
- samtools/misc/ace2sam.c.pysam.c
- samtools/samtools.pysam.c
- samtools/samtools.pysam.h
I re-ran the import scripts using the following commands, starting from the branch in #706:
```
tar -jxvf htslib-1.9.tar.bz2
rm -rf htslib
mv htslib-1.9 htslib
echo '#define HTS_VERSION "1.9"' > htslib/version.h
tar -jxvf samtools-1.9.tar.bz2
rm -rf samtools
python devtools/import.py samtools samtools-1.9/
echo '#define SAMTOOLS_VERSION "1.9"' > samtools/version.h
tar -jxvf bcftools-1.9.tar.bz2
rm -rf bcftools
python devtools/import.py bcftools bcftools-1.9
echo '#define BCFTOOLS_VERSION "1.9"' > bcftools/version.h
git checkout htslib/htslib.pc.tmp
git checkout bcftools/config.h
```
> Fix EOF issue, part 3

- devtools/import.py
- import/pysam.c
- import/pysam.h
Rather than trying to rewrite a function call as two function calls when we don't really know what the syntax around the call site looks like, rewrite it as a call to our own function.
I haven't actually run this, but assuming the regexp syntax is right you should get the idea. Needs a followup commit to actually run _import.py_ over the freshly imported source code.
> Really fix this import.py fputs != EOF && fputc != EOF madness

- tests/pysam_data/Makefile
It is just something one notices when packaging for Debian.
> pysam_data: cleaning of generated with_md.sam.gz

- MANIFEST.in
* This caused the PyPI tarballs to miss the stubs
required for building htslib on macOS. This would
not show up for source-tree builds, as the files
are included in git, just not in `MANIFEST.in`.
Fixes #645
@AndreasHeger could you maybe issue a 0.15.1.1 release on PyPI after merging this? Without this, installing pysam is really painful on macOS and requires people to use an ancient version without overlong CIGAR support.
> Add missing macOS stub files in `MANIFEST.in`

- pysam/libcalignedsegment.pyx
I  noticed that in pysam 0.15.1, there is a bug with the get_aligned_pairs function when matches_only=True and with_seq=True.  Basically, the read position gets advanced, but the reference position does not.  This fixes that bug, and I believe it won't involve changing any other portions of the code.
> Fix bug in get_aligned_pairs

- .travis.yml
See https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration
> Remove deprecated sudo: false from .travis.yml

- .travis.yml
- devtools/run_tests_travis.sh
Bump the samtools/htslib/bcftools versions used. Pinning 1.7 means Pysam testing is stuck forever at the broken-openssl/libcrypto condapocalypse.
At least, that's a theory on how to get around [these macOS failures](https://api.travis-ci.org/v3/job/512462692/log.txt):
```
dyld: Library not loaded: @rpath/libcrypto.1.0.0.dylib
Referenced from: /Users/travis/miniconda3/envs/testenv/bin/samtools
Reason: image not found
./devtools/run_tests_travis.sh: line 48:  2127 Abort trap: 6           samtools --version
```
> Fix travis builds

- .travis.yml
- devtools/import.py
- devtools/run_tests_travis.sh
- tests/AlignmentFile_test.py
- tests/TestUtils.py
- tests/samtools_test.py
- tests/tabix_test.py
- tests/tabixproxies_test.py
1. Use `checkGZBinaryEqual` to compare BAM files, as the more recent samtools build likely uses libdeflate rather than zlib — which introduces spurious differences in the compressed streams.
2. Bump the samtools/htslib/bcftools versions used. Pinning 1.7 means Pysam testing is stuck forever at the broken-openssl/libcrypto condapocalypse.
3. Force ncurses to come from conda-forge channel to overcome various known issues.
4. Add py37 to Travis matrix
5. Remove python 3.4 and 3.5 from Travis matrix, as they are no longer supported on Bioconda and conda-forge
6. Clean up conda channel setup to match https://bioconda.github.io/
7. Use raw strings for regular expressions to avoid Python 3.7 "DeprecationWarning: invalid escape sequence".
> Fix Travis samtools etc versions and BAM comparisons

- pysam/libcalignmentfile.pyx
- pysam/libcfaidx.pyx
Some docstrings start with 4 quote characters instead of 3 which then shows up as e.g.
> “bool indicating the current state of the file object.
in the [documentation](https://pysam.readthedocs.io/en/latest/api.html#pysam.FastxFile.closed). This PR remove the extra characters.
> Fix extra quotes in docstrings

- doc/glossary.rst
samtools compatible region string should be like  ‘chr1:10000-20000’ rather than ‘chr1:10000:20000’. The example is wrong. The code of parse_region (https://github.com/pysam-developers/pysam/blob/9961bebd4cd1f2bf5e42817df25699a6e6344b5a/pysam/libchtslib.pyx#L667) is correct.
> Fix doc of region example in glossary

- doc/usage.rst
This pysam.calignmentfile should be pysam.libcalignmentfile.
In version 0.10.0 and onwards, all pysam extension modules contain a lib-prefix. This facilates linking against pysam extension modules with compilers that require to start with lib. As a consequence, all code using pysam extension modules directly will need to be adapted. 
Fount at https://github.com/pysam-developers/pysam/blob/aa27e81b123067427ae08f5345feb891b7efa857/doc/faq.rst#importerror-cannot-import-name-csamtools
> Fix documentation Extending pysam

- pysam/libcalignedsegment.pxd
- pysam/libcalignedsegment.pyx
- pysam/libchtslib.pxd
Use HTSlib's `kstring_t`, which reallocates and enlarges its memory as needed, rather than a fixed-size char buffer. Fixes #717.
> Remove string buffer size limit in get_query_sequences()

- pysam/libcalignmentfile.pyx
For CRAM files, HTSlib iterators are in fact a stub struct — the real iterator limits are stored within the cram_fd itself, having been set via `cram_set_option(CRAM_OPT_RANGE)`. This means that reopening the CRAM file as a new cram_fd, which happens with `multiple_iterators=True`, is problematic as the iterator limits don't apply to the separate cram_fd.
Avoiding reopening the CRAM file fixes #725.
I was tempted to do something similar in `IteratorColumnAllRefs` but that one works as is (though I don't especially see why!). To be honest, it's not clear what `multiple_iterators=True` is for in general…
> Default to multiple_iterators=False for pileups

- pysam/libcbcf.pyx
avoids the problem described at https://github.com/pysam-developers/pysam/issues/773
> do not cache VariantRecord.id to avoid memory leak from pysam-developers#773

- pysam/libcbcf.pyx
There is an extraneous `.format` parameter
> Fix incorrect error message

- pysam/libcbcf.pyx
This PR does bare minimum to support unicode literals in VCF files.
Related to #445 .
Ran the unit tests, PR hasn't affected them:
374 failed, 547 passed, 15 skipped, 2 warnings in 73.56 seconds (with and without my changes).
> Add basic support for UTF-8 strings in libcbcf.pyx.

- doc/api.rst
Add class AlignmentHeader to the API documentation.
> Include AlignmentHeader class in API documention

- doc/usage.rst
Tiny fix for the correct formatting of a code block. Turns
into
> Fix code block formatting for `tbx.fetch` usage

- .travis.yml
when tagging a release.
Build Linux and macOS binary wheels using cibuildwheel.
Build sdist with libcurl and s3 support.
Upload sdist and wheels to PyPI using twine.
xref. https://github.com/pysam-developers/pysam/issues/722
> Build wheels and upload them to PyPI

- devtools/run_tests_travis.sh
- htslib/configure
- htslib/configure.ac
- setup.py
Prevent build failures by ensuring that `configure` uses the same compiler and CFLAGS/etc that will be used later when the Cython and C source itself is compiled.
In particular, the sysconfig $CFLAGS (oddly enough) prevents the compiler from searching /usr/local/include (at least on macOS). Without this PR, configure sees (Homebrew/etc's) /usr/local/include/lzma.h so defines `HAVE_LZMA_H`; later when compiling htslib/cram/cram_io.c that directory is not searched, leading to `<lzma.h> not found` errors. Ensuring that configure also does not see lzma.h there leaves `HAVE_LZMA_H` undefined, which activates HTSlib's os/lzma_stub.h workaround for this header being missing and leads to an lzma-enabled pysam using macOS's system liblzma.dylib.
Fixes #495. Fixes #828.
[It appears I didn't submit …
> Run configure with the correct CC/CFLAGS/LDFLAGS env vars

- pysam/libcbcf.pyx
Due to identical return code of `-1` for cases where the end of the file is reached (non-error case) from cases where an error during parsing occurred (e.g. due to incorrect type of field), it is now reading out the error code that may be set inside the `bcf1_t*` record.
In this way, `pysam` can raise an exception and the user is able to properly handle it instead of having a putatively successful read and the burden to check the stderr for any messages like `[E::vcf_parse_format]` or to check whether the total number of records has been processed.
> Attempt to fix of #799.

- pysam/libcbcf.pyx
Currently, when a record is malformed and has less than 2 tabs (aside from trailing), referencing `*ptr.d.id` causes segmentation fault. By checking `m_id`, we can tell if any memory was allocated, and if not, fail gracefully.
Example malformed line:
```
#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT
1\t1\t\t
```
Ran `pytest tests`, same tests pass/fail, with or without the change.
> Prevent segmentation fault on ID, when handling malformed records.

- pysam/libcfaidx.pyx
Prior to this commit, `pysam` silently truncates FASTQ files that have bad quality strings. For instance, consider the following code which attempts to read a FASTQ file where the quality string is invalid because it differs in length from the sequence:
import tempfile
import pysam
with tempfile.NamedTemporaryFile('wt') as f:
f.write('>name\nACT\n+\n????')
f.flush()
nreads = len([r for r in pysam.FastxFile(f.name)])
print(nreads)
Prior to this commit, the above code would return 0 even though there is in fact 1 invalid entry in the FASTQ. The reason is that in the code, `kseq_read` returns -1 for end of file but -2 for truncated quality string, but the code for `FastxFile` assumes end of file for any return < 0.
With this commit, an error is now raised for invalid FASTQ files rather than …
> Fix silent truncation of FASTQ with bad q strings

- pysam/libcalignedsegment.pyx
- pysam/libcalignmentfile.pyx
- pysam/libchtslib.pyx
There are currently lots of bits of garbled documentation at https://pysam.readthedocs.io/en/latest/api.html where Napoleon either rendered a multi-line description wrongly, or chucked in some cruft like the text `:param` for no obvious reason. I don't really understand Napoleon (or even vanilla Sphinx/RST), but with some random tinkering around, I've managed to come up with this PR that makes all the really broken stuff I could spot go away.
> Fix lots of broken docs formatting

- pysam/libcutils.pyx
Please see [#862](https://github.com/pysam-developers/pysam/issues/862)
> Force arg to bytes to support non-ASCII encoding

- setup.py
Import is overwritten in the next line with cy_build
> Removal of unused import

- .travis.yml
- Use cibuildwheel>=1.1.0 to allow specifying the `-L .` option for the auditwheel command. Introduced in joerick/cibuildwheel#211 . Fix #831 .
- Split sdist and linux deploy in 3 separate jobs, otherwise the Travis job times out after 50'.
> Fix wheel building on TravisCI

- pysam/libcalignedsegment.pyx
- tests/AlignedSegment_test.py
Comparing an `AlignedSegment` object to `None` throws a Segmentation Fault, when running on Python 2.7.  Using Python 3 did not yield the segfault in a one-off test.
The specific condition to throw the segfault is when testing object equality.  Instance equality seems to work fine.
```
a = pysam.AlignedSegment()
b = None
a is b   # False
a == b # segfault
a.compare(b) # segfault
```
The submitted PR includes additions to the unit tests to reproduce the segfault, as well as the fix.  The current workaround is for users to use the `is` operator when `None` is a potential comparison argument.
As stated before, this issue was reliably reproduced on the following, using Python 2.7.
**Docker images**
- `python:2.7.17-slim-buster`
- `python:2.7.17-alpine`
- `centos:7.5.1804`
**Bare Metal & KVM** …
> Prevent segfault on Python 2.7 AlignedSegment.compare(other=None)

- doc/faq.rst
Fixes two small typos in the FAQ documentation.
> Fix typos in the FAQ

- pysam/libcalignmentfile.pxd
- pysam/libcalignmentfile.pyx
Reorganise `pileup` so that it chooses between `IteratorColumnRegion`/ `IteratorColumnAllRefs`/ `IteratorColumnAll` primarily by `has_coord` (i.e., whether `contig`+etc/`region` was specified) and secondarily by `has_index`.
Add `IteratorColumnAll()` which iterates as per HTS_IDX_REST, piling up the entire file, which works without an index and for SAM files. (Unfortunately `sam_itr_next()` does not work for SAM files (even for HTS_IDX_REST) prior to HTSlib 1.10. Instead we follow `samtools mpileup`'s
lead and special case this to use `sam_read1()` at the bottom level instead of `sam_itr_next()`.)
The common parts of the two `_setup_iterator` functions could in future be refactored…
> Implement pileup() for unindexed files and/or SAM files

- pysam/libcbcf.pyx
- pysam/utils.py
Fixes #909. This pull request addresses the quoting issue when adding contigs to a VariantFile's header. In addition, I implemented a more generic solution that disables quoting of attribute values by tagging those values with `unquoted_str`. This may be helpful for addressing similar issues with other types of meta-information.
> Fix incorrect quoting in VariantFile contig records

- doc/release.rst
- pysam/version.py
Release candidate for v0.16.0 release - apologies for the delay.
Hi @bioinformed  and @jmarshall , is there anything you think I should wait for?
Otherwise I will update the docs and push out the release.
> {AH} bump version to 0.16.0

- doc/faq.rst
Missing 1 backtick, which means the existing backticks appear in the documentation instead of showing the snippet as code.
> Missing backtick

- pysam/libcalignmentfile.pxd
The definitions in `pysam/libcalignedsegment.pxd`/`.pyx` seem to be the ones that are currently used, while these apparently are leftovers from some refactoring.
> Remove duplicate cdefs of PileupRead/-Column

- MANIFEST.in
- pysam.py
When running `python3 -c "import pysam"` in the repository root, "pysam.py" is actually ignored because `pysam/__init__.py` exists and is used instead.
I think the risk of a regular user trying to use pysam from a Git clone are quite low nowadays. Also, running `python3 setup.py build_ext -i` actually allows `import pysam` from the repo root to work.
> Remove pysam.py as it doesn’t fulfill its purpose

- pysam/libcbcf.pyx
- pysam/libcutils.pxd
- pysam/libcutils.pyx
Python has impressively flexible facilities to control how the [decode() function](https://docs.python.org/3/library/stdtypes.html#bytes.decode) deals with unexpected input.
The easiest way to enable scripts to control pysam's use of the `decode()` function is to expose this as a global variable via getter/setter methods, similarly to the existing `get_verbosity()`/`set_verbosity()`.
For convenience, also define an error handler that simply interprets invalid/unexpected UTF-8 bytes as ISO-8859-1 (Latin-1) characters. Make it available via `set_encoding_error_handler('pysam.latin1replace')`.
Issue #998 is about pysam's basic UTF-8 parsing refusing to parse fields containing Latin-1-encoded accented letters. This PR would allow scripts to parse such fields by adding:
```python …
```
> Add get/set_encoding_error_handler() to control UTF-8 conversion

- pysam/libcalignmentfile.pyx
- tests/AlignmentFile_test.py
- tests/pysam_data/Makefile
- tests/pysam_data/make_corrupt_bam.sh
For the iteration methods backed internally by `sam_read1`, _all_ return
codes < -1 signify errors which should raise an exception to the user.
***
I recently had a BAM file that had been corrupted somehow during download, but when I iterated over it with `pysam.Samfile`, iteration ended prematurely but silently - that is, no exceptions were thrown when the corrupted region of the BAM was reached, only some warnings were printed to the terminal by htslib. Example output:
```
>>> f = pysam.Samfile("mapped.bam", "rb") ; sum(1 for _ in f)
[E::idx_find_and_load] Could not retrieve index file for 'mapped.bam'
37954048
>>> f = pysam.Samfile("mapped_corrupt.bam", "rb") ; sum(1 for _ in f)
[E::idx_find_and_load] Could not retrieve index file for 'mapped_corrupt.bam'
[E::bgzf_uncompress] CRC32 …
```
> Better handling of file iteration errors

- doc/api.rst
For me, the pysam API is the most important part of the documentation, and I think the "API" section should therefore be at the top level.
I’m suggesting this change because I never seem to be able to find that section on first attempt when browsing the docs, mostly because it is somewhat hidden below the first heading "pysam - An interface for reading and writing SAM files".
While writing this, I realized that there is actually a full table of contents on the landing page https://pysam.readthedocs.io/en/latest/, which would allow me to go to the API section with a single click, but the fact that I haven’t seen it at least a dozen times makes me believe that having it also in menu on the left would be an improvement.
> Make "API" a top-level heading

- pysam/libcalignedsegment.pyx
This patch applies `s/query_alignment_length/template_length/` so fixes #1040. While in the neighbourhood, it also proposes altering the display of the RNAME, POS, RNEXT, and PNEXT fields.
The `__str__` function (also used when you simply `print` an AlignedSegment object) is a simplified way of printing an alignment record, and takes some shortcuts because a set of headers might not be available.
For full writing or printing of a SAM record, you would be writing to an `AlignmentFile` or using `rec.to_string()`, both of which take advantage of headers to print the chromosome names and use htslib facilities to print the record in proper SAM format.
`__str__` prints a half-internal form of this: RNAME/RNEXT are shown as the `tid` integer (i.e. 0 ≤ _tid_ < _nchroms_) instead of the actual …
> Improve `AlignedSegment.__str__` and `print(read)` field display

- Containerfile
After running into #1044 I've started exploring this path. And here the installation "just worked". If we provide a base image with the pysam package then people can build their tooling on top of that baseimage in any OS that runs containers in a similar fashion.
I built and tested it this way:
```
$ podman build -t pysam -f Containerfile .
$ podman run -it pysam python -c "import pysam; print('woohoo')"
```
Let me know what you think.
> baseimage for containers

- pysam/libcalignedsegment.pyx
Some of the attribute docstrings refer to deprecated attributes. For example, `reference_length` is described as being equal to `aend - pos`. This PR fixes those outdated descriptions.
> No longer refer to deprecated attributes in AlignedSegment attribute descriptions

- .github/workflows/ci.yaml
- cy_build.py
- pysam/__init__.py
- setup.cfg
- setup.py
- tests/AlignmentFileFetchTestUtils.py
- tests/AlignmentFileFetch_bench.py
- tests/AlignmentFileHeader_test.py
- tests/AlignmentFilePileup_bench.py
- tests/PileupTestUtils.py
- tests/TestUtils.py
- tests/VariantFileFetchTestUtils.py
- tests/VariantFile_bench.py
- tests/VariantFile_test.py
- tests/VariantRecord_test.py
- tests/faidx_test.py
- tests/tabixproxies_test.py
- tests/test_samtools_python.py
Whenever I open up the pysam source code in PyCharm, I get a lot of warnings from the built-in code style checker: Unused imports, weird indentation, too many blank lines, trailing whitespace etc. ... I have somewhat gotten used to working with code that uses an automatic style checker, mostly flake8, so I wonder if this would be something that could be considered for pysam.
In this PR, I’ve
- added a "lint" job to the GitHub Action workflow that runs `flake8`
- configured `flake8` to ignore all the existing problems it finds
- re-enabled a couple of these checks while at the same time fixing them in the source code
The idea is to re-enable the checks one by one. I can do this for some of the checks if there’s interest.
I’m aware that style checking is a matter of personal preference, and …
> Run flake8 and fix some linting issues

- bcftools/bcftools.pysam.c
- bcftools/bcftools.pysam.h
- import/pysam.c
- import/pysam.h
- pysam/libcbcftools.pxd
- pysam/libcsamtools.pxd
- pysam/libcutils.pyx
- samtools/samtools.pysam.c
- samtools/samtools.pysam.h
The `getopt()` and `getopt_long()` functions have internal state tracking the option parsing that needs to be reset when user code wants to start processing a different `argc`/`argv` pair, i.e., when running a samtools or bcftools command (apart from the first time such a command is run in a Python session).
7954ff1a6df7a4a7e088e7b17bfd4e9868bb94dc improved resetting on macOS but broke it on Linux. This PR rewrites it to work on both platforms. Resetting is not standardised by POSIX but varies by C library:
* GNU libc defines its own way by setting `optind` to 0. (This is barely documented, but is described in the _getopt.h_ header.)
* BSD-derived systems use an extra `optreset` variable, which can be detected via a preprocessor symbol: some BSDs define `_OPTRESET_DECLARED`, while macOS …
> Improve getopt()/getopt_long() resetting when running samtools/bcftools commands

- pysam/libcbcf.pyx
- pysam/libchtslib.pxd
- tests/VariantFile_test.py
This adds a read-only property `alleles_variant_types` to `VaraintRecord`.
In the past, I've needed a way to check variant types when processing VCF files (splitting/counting records or samples based on type). The HTSlib function `bcf_get_variant_type` can be used for this but is not currently exposed via pysam.
This new property returns a tuple containing the type of each variant in `VaraintRecord.alleles`. 
(I couldn't decide on the right name, but wanted to associate it with `VariantRecord.alleles` as it returns a tuple of the same length but with the type of each allele - happy to change it to something better.)
> Add VariantRecord.alleles_variant_types

- pysam/libcbcf.pyi
Gets made into a string here:
https://github.com/pysam-developers/pysam/blob/5eac009c5e85d280e8bbcb69ed0fa081e2271d78/pysam/libcbcf.pyx#L1587
> Fix type of VariantHeaderMetadata add

- pysam/libcbcf.pyx
- tests/VariantRecord_test.py
This is a fix for issue #891 .
The cause of the issue is that in `libcbcf.pyx`  the `@alleles.setter` method is identical to the `@allele_indices.setter` method, while it should calculate the the allele indices and write these to the GT. 
I have included a test to check the correct behavior.
Additionally there is some code to allow the GT to be reset by passing `None` an empty tuple or a `(None,)` tuple, and finally an assertion to check if no integers are passed to inform (potential) users which expect the old but incorrect behavior.
> Fix setting sample genotype using .alleles property

- cy_build.py
Hey,
I ran into an issue installing pysam with python 3.11.0. It seems that the `SO` configuration has been deprecated and `EXT_SUFFIX` should be used instead.
Also note that using `get_config_var` to access would have likely triggered a deprecation warning :)
Lets see what the actions say, but in case this causes test failures for older versions, I can adjust this to make it conditional.
Cheers
> Get shared object suffix from `EXT_SUFFIX`

- pysam/bcftools.py
- pysam/samtools.py
- pysam/utils.py
> populate symbols for samtools and bcftools.

- pyproject.toml
This PR allows pip isolated builds to work, but still uses the same build infrastructure as always, so shouldn't break anything.
I needed this because I develop a pipeline running on python 3.11, for which there isn't a wheel yet. The dependency manager I'm using ([poetry](https://python-poetry.org/)) does all its builds in isolated environments, which is fine when `setup.py` doesn't depend on anything except `setuptools` and/or `wheel` but has problems when you need e.g. `cython`
The solution is to add a minimal `pyproject.toml` file that includes the build dependencies, and specifies the correct build backend. That way, the isolated enviroment used for the build ends up with Cython, and everyone is happy.
I added some stuff to the project description, but this is all already in …
> Add a minimal pyproject.toml for PEP517 

- .github/workflows/ci.yaml
Python 3.11 is now the first actions/setup-python Python built to target universal2 (i.e., x86_64/arm64 multiarch) on macOS. (I think in the past 3.9 and 3.10 were also built to target universal2 for a while — at least, ISTR seeing multiarch builds on earlier Python versions — but this was later reverted; see actions/python-versions#114.)
Brewed packages such as xz (which provides liblzma.dylib and liblzma.a) are built for only a single native architecture. This led to build and configure failures when the native-only liblzma.dylib was linked against by a multiarch compilation.
Work around this by unlinking the xz package so that this brewed library is not found by the linker, failing back to the system .tbd file instead. If later build steps use brewed commands that need this library, we …
> Fix multiarch macOS build by removing brewed liblzma

- pyproject.toml
It's only needed at build time.
Should fix https://github.com/galaxyproject/galaxy/pull/15942/files#r1167475501
> Remove cython from runtime dependencies

- htslib/htslib/kseq.h
An original fix was submitted by [@kloetz](https://github.com/kloetzl) to seqtk repo. Improves FASTA parsing to 2GB/s . 
See: 
- https://github.com/lh3/seqtk/pull/123
- https://twitter.com/kloetzl/status/1661679452479266818
> fix: improve parsing performance

- .github/workflows/ci.yaml
- .github/workflows/release.yaml
- pysam/libcutils.pyx
Fix 6½ year old incorrect `cimport` statements that accidentally depended on `get_pysam_version()`'s addition to `sys.path`.
Add a second test commit (which hardcodes a version number in place of the existing `get_pysam_version()` code) temporarily to do a full CI check on the change.
That succeeded (see 2d67777b1c2d80bef1753c66bb0c36e18f78a9dc and [run 6466884695](https://github.com/pysam-developers/pysam/actions/runs/6466884695)); replace it with some minor actions workflow updates, to test them.
> Use relative cimports rather than luck

- pysam/libcalignedsegment.pyx
Before:
```
<pysam.libcalignedsegment.AlignedSegment object at 0x7fd74c3ae2c0>
```
After:
```
<AlignedSegment('name', flags=16, ref='chr1', pos=1170070, mapq=255, cigar='50M', ...)>
```
I’ve used pysam with this patch for a while and find it very valuable when looking at `AlignedSegment`s in a debugger or the REPL.
I’ve chosen to include only the (from my perspective) most important attributes so that the output doesn’t become too long, in particular when there’s a list with `AlignedSegment`s.
The angle brackets are supposed to convey that the string cannot be passed to `eval()` to recreate the object. I’d be fine with removing them.
> Add AlignedSegment.__repr__

- pysam/bcftools.py
- pysam/libcutils.pyx
- pysam/samtools.py
- pysam/utils.py
- tests/samtools_test.py
- tests/typechecking_test.py
As reported in PR #1306, mypy rejects `pysam.view(…)` et al because it doesn't know that they exist. This is due to the definition of `__all__` in _pysam/samtools.py_: either `HAVE_FINAL` is True for mypy so it skips the `__all__` definition, or the definition is complex enough that mypy does not evaluate it, or both (as #1306 did not fix the problem).
The first commit fixes this by lifting the `__all__` definition to the top-level and making it a simple assignment of a literal list. The second commit simplifies the rest of the code in _pysam/samtools.py_ and _pysam/bcftools.py_.
> Fix typechecking for top-level samtools commands like `pysam.view(…)`

- pysam/libcalignmentfile.pyx
The message for the type error when creating a SAM header from a dictionary misses type names. The following MWE causes the error by passing a dictionary instead of a list of dictionaries under the **PG** tag in the SAM header:
```
import pysam
header = {"PG": {"ID": "my-tool"}}
output = pysam.AlignmentFile("test.sam", "w", header=header)
```
The current invalid-type error message:
```
ValueError: invalid type for record %s: %s, expected %s
```
The fixed error message:
```
ValueError: invalid type for record PG: <class 'dict'>, expected <class 'collections.abc.Sequence'>
```
> Fix invalid-type message for creating header from dictionary

- pysam/libcalignedsegment.pyx
- setup.py
Cython 3.1.0, released last week, changed the way enums work:
> Named `cpdef enums` no longer copy their item names into the global module namespace. This was considered unhelpful for named enums which already live in their own class namespace. In cases where the old behaviour was desired, users can add the following backwards compatible command after their enum class definition: `globals().update(TheUserEnumClass.__members__)`. Anonymous enums still produce global item names, as before.
For upcoming patch releases, this PR restores the status quo of having both
`pysam.CIGAR_OPS.CMATCH` and `pysam.CMATCH` et al. It applies a (modified form of) the suggested fix. Fixes #1339.
In a future minor release, we will likely remove this shim and require Python code to use `pysam.CIGAR_OPS.CMATCH` …
> Explicitly add enum members as global names

- pysam/libcalignedsegment.pyx
- tests/AlignedSegment_test.py
Use direct string manipulation instead of inefficient Python joins
> Improve cigarstring performance
