pysam-developers/pysam

- pysam/calignmentfile.pyx
- tests/AlignedSegment_test.py
Tiny patch to pull request #95 - only need to do the boolean conversion once.
> Get aligned pairs tiny speedup

- pysam/calignmentfile.pyx
- tests/AlignmentFile_test.py
This pull request introduces a function to quickly count coverage in a given region.
I reach about a 26x speed up compared to the pure python implementation.
> Introduced AlignmentFile.count_coverage

- pysam/cbcf.pyx
* VariantHeader is now mutable
* VariantHeaderRecord objects now act like mappings for attributes
* Added VariantHeader.alts dict from alt ID->Record.
* Bug fix to string representation of structured header records.
> BCF fixes and start of read/write support

- pysam/cbcf.pyx
* Add mutable properties to VariantRecord
* Add `phased` property on `VariantRecordSample`
* Release GIL around htslib IO operations
> More work on read/write support, API improvements

- pysam/cfaidx.pyx
Allows FastaFile to be used in a 'with' statement.
> adds context manager functions to FastaFile

- pysam/cvcf.pyx
The rest of the changes are whitespace trimming, sorry about that.  The only real changes  should be at the top of the file.  Before and after docstrings are shown below.  Not sure how you feel about my additional note in the comments, but I had no idea about the difference between VariantFile and VCF until I looked through the source code---I thought a note would be in order.
```
v = pysam.VCF()
v.write?
Docstring: Writes a VCF file to a stream, using a data generator (or list)
Type:      instancemethod
[...]
v = pysam.VCF()
v.write?
Docstring:
VCF.write(self, stream, datagenerator)
Writes a VCF file to a stream, using a data generator (or list)
Type:      instancemethod
```
> Added function signatures to cvcf cython.  Added note about other VCF code.

- doc/usage.rst
*fromQualityString* was renamed to *qualitystring_to_array*
> Update docs to keep up with code changes

- pysam/cbcf.pxd
- pysam/cbcf.pyx
- tests/VariantFile_test.py
- tests/cbcf_data/Makefile
Addresses issue #87 for @jeromekelleher
> Add index filename specification to VariantFile API

- doc/installation.rst
> Fix docs typo.

- tests/test_samtools_python.py
It seems my test wasn't quite py3k compatible.  Let's see if this does the trick.
> Fix test on py3k

- setup.py
Tabixproxies and vcf couldn't locate the htslib dirs during a manual install. Added these to the respective parts in the setup script.
> #262 Fix install issue

- doc/faq.rst
> typo fix in update.rst

- pysam/calignmentfile.pyx
Related to issue 71, although it wasn't giving me any errors, it just silently removed `PM` from `@RG`.
> include PM in RG header tag order list

- README.rst
Given that people are currently having lots of install issues, it may make sense to direct people to the bioconda packages.  Up to you.
> Add bioconda instructions?

- setup.py
This is a patch I have applied in order to build the Debian package using the system htslib installation. I've tried to make it flexible so that it still works for the other two cases you support.
> Improve handling of build system for external htslib

- pysam/__init__.py
- pysam/cbcf.pxd
- pysam/cbcf.pyx
- pysam/cbgzf.pyx
- setup.py
Fix #259 Error loading empty VCFs (due to empty index)
Fix mode specification and validation for VariantFile [API change!]
Add pysam.BGZFile reader and writer object [WIP - needs testing]
Add initial support for removing header lines. [WIP - still very dangerous]
> Merge dev progress

- pysam/cbcf.pyx
Small fix + minor new feature requested by Erik Gafni
> Fix id check; add method to add filters

- pysam/cbcf.pxd
- pysam/cbcf.pyx
- pysam/chtslib.pxd
- tests/VariantFile_test.py
It is still possible to crash Python with a segfault, but at least it is harder to do now.
> Address issue #314 and other work to prevent crashes and make the API safer.

- pysam/libcbgzf.pyx
[#411] Fix BGZfile initialization bug
[#412] Add seek support for BGZFile
[#395] Make BGZfile iterable
> Address several outstanding BGZfile issues

- pysam/libcalignedsegment.pyx
- tests/AlignedSegment_test.py
> [#433] correct getQueryEnd

- pysam/libcfaidx.pyx
- tests/faidx_test.py
- tests/pysam_data/Makefile
> {AH} reactivate filepath_index, fixes #270

- pysam/libcalignmentfile.pxd
- pysam/libcalignmentfile.pyx
- tests/AlignedSegment_test.py
- tests/AlignmentFileHeader_test.py
- tests/AlignmentFile_test.py
fix a \0 issue in header, refactor AlignmentHeader
use class method factory methods
> {AH} AlignmentHeader revision

- README.rst
- setup.py
> Fix setup.py out of date info

- tests/tabix_test.py
Fixes: https://github.com/pysam-developers/pysam/issues/761
> Test Tabix index contents, not the compression

- .travis.yml
- devtools/run_tests_travis.sh
Reverts pysam-developers/pysam#782
cc @jmarshall
> Revert "Fix travis builds"

- pysam/libcalignedsegment.pyx
> Fix docstring

- tests/VariantFile_test.py
- tests/cbcf_data/example_vcf43.vcf
- tests/cbcf_data/example_vcf43_with_utf8.vcf
adds some tests for unicode support.
> {AH} add unicode tests

- .travis.yml
> Restore twine upload on tag

- pysam/libcalignmentfile.pyx
> Fix doc for AlignmentFile.get_reference_length()

- setup.py
This now appears to live in devtools/import.py
> Remove unused constant from setup.py

- setup.py
I saw that it is currently necessary to run `python setup.py build` before `sdist` to ensure that the generated tarball contains cythonized sources. This means that generating the tarball creates a couple of minutes.
With this PR, `python setup.py sdist` will cythonize the sources before bundling the tarball. This takes only a couple of seconds.
My intention is to use this in the CI tests: It would be nice to generate the tarball in a separate job (with the development dependencies installed), and then start a new job to install it (without developer dependencies installed). This more closely resembles what happens on a user’s system.
If Cython isn’t installed, `python setup.py sdist` will raise an ImportError when running `python setup.py sdist`. IMO the resulting error message …
> Ensure "python setup.py sdist" cythonizes extension modules

- .travis.yml
Closes https://github.com/pysam-developers/pysam/issues/1029
@jmarshall, can you please take a look into this PR?
> Add aarch64 wheel support

- .github/workflows/ci.yaml
- .github/workflows/release.yaml
- AUTHORS
- doc/release.rst
- pysam/version.py
Add CI for wheel building in github actions.
Update release notes for 0.17.0
> Release 0.17.0

- .github/workflows/release.yaml
> Add Linux AArch64 wheel build support

- pysam/libcbcf.pyi
See: https://github.com/pysam-developers/pysam/blob/5eac009c5e85d280e8bbcb69ed0fa081e2271d78/pysam/libcbcf.pyx#L2120-L2124
> Fix typing of new_record from VariantHeder

- .github/workflows/release.yaml
* use latest version of cybuildwheel to fix build issues.
closes #1182
> fix-cybuildwheel-version
